# -*- coding: utf-8 -*-
"""
Created on Fri Jun 10 13:06:06 2016

@author: ericgrimson

---
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def fib(x):
    """assumes x an int >= 0
       returns Fibonacci of x"""
   
    if x == 0 or x == 1:
        return 1
    else:
##        print(i) ## ancient man,, very antique
        return fib(x-1) + fib(x-2)
            
def impar(lim, maxFib):
    '''
    Define quais números Fibonacci vindos de fib(x) são ímpares.
    '''
    fib_num = 0
    soma_impar = 0
    contagem = 0

    for i in range(1, lim):
        fib_num = fib(i)
        if fib_num >= maxFib:
            break
        print("-> Fibonacci de: ", i, "=", fib_num)
        if fib_num%2 != 0:
            soma_impar += fib_num
            contagem += 1
            print("** Impar: ", fib_num, "Impar n.: ", contagem, "Soma =", soma_impar)